<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot Parent -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>

    <!-- Project Information -->
    <groupId>com.vignesh</groupId>
    <artifactId>enterprise-ai-assistant</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>enterprise-ai-assistant</name>
    <description>Enterprise AI Knowledge and Support Platform</description>

    <!-- Java -->
    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>

        <!-- =============================== -->
        <!-- Spring Boot Web                  -->
        <!-- =============================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc</artifactId>
        </dependency>

        <!-- =============================== -->
        <!-- Spring Boot DevTools              -->
        <!-- =============================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <scope>runtime</scope>
            <optional>true</optional>
        </dependency>

        <!-- =============================== -->
        <!-- LangChain4j Spring Boot 4        -->
        <!-- =============================== -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-spring-boot4-starter</artifactId>
            <version>1.18.1-beta28</version>
        </dependency>

        <!-- =============================== -->
        <!-- LangChain4j OpenAI-compatible    -->
        <!-- Groq uses OpenAI-compatible API  -->
        <!-- =============================== -->
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-open-ai-spring-boot4-starter</artifactId>
            <version>1.18.1-beta28</version>
        </dependency>

        <!-- =============================== -->
        <!-- Testing                           -->
        <!-- =============================== -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-embeddings-all-minilm-l6-v2</artifactId>
    <version>1.18.1-beta28</version>
</dependency>
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j</artifactId>
    <version>1.18.1</version>
</dependency>

    </dependencies>

    <!-- Spring Boot Maven Plugin -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>