spring.application.name=enterprise-ai-assistant

langchain4j.open-ai.chat-model.base-url=https://api.groq.com/openai/v1
langchain4j.open-ai.chat-model.api-key=${GROQ_API_KEY}
langchain4j.open-ai.chat-model.model-name=openai/gpt-oss-120b
langchain4j.open-ai.chat-model.temperature=0.0